## pandas 

In [1]:
# importing pandas and numpy
import numpy as np
import pandas as pd

In [2]:
#creating just the array of the shape 5*4 matrix
np.arange(0,20).reshape(5,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [3]:
# dataframe creation
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=['row1','row2','row3',
                                                     'row4','row5']
             ,columns=["column1","column2","column3","column4"])

In [4]:
df

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [5]:
# looking the first five rows of dataframe(df)
df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [6]:
#type of the df
type(df)

pandas.core.frame.DataFrame

In [7]:
df['column2'].unique()

array([ 1,  5,  9, 13, 17])

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row1 to row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column1  5 non-null      int32
 1   column2  5 non-null      int32
 2   column3  5 non-null      int32
 3   column4  5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [9]:
df.describe()

column1    column2    column3    column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [10]:
## checking the indexing:
   ##1.)direct by using column name
    ##2.) rowindex number
    ## 3.) column index no

 ##### 1.)direct by using column name

In [11]:
df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [12]:
 # by using the column name 
df[['column1','column2','column3']]


column1  column2  column3
row1        0        1        2
row2        4        5        6
row3        8        9       10
row4       12       13       14
row5       16       17       18

In [13]:
#checkcing the type 
type(df[['column1','column2','column3']])
# it is  the dataframe 

pandas.core.frame.DataFrame

In [14]:
# taking only one column 
df['column1']

row1     0
row2     4
row3     8
row4    12
row5    16
Name: column1, dtype: int32

In [15]:
# it is series 
type(df['column1'])

pandas.core.series.Series

##### 2.) rowindex number

In [16]:
# olny one row
df.loc['row3']

column1     8
column2     9
column3    10
column4    11
Name: row3, dtype: int32

In [17]:
df.loc[['row1','row2','row3']]

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11

##### 3.)index location 


In [18]:
#index location is used , that is the combination of both  1 ,2 

In [19]:
df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [20]:
#  rows index no. starts from 0 , 1 ,2,3...............
#  column index no. starts from 0 , 1 ,2,3...............
   

In [21]:
 df.iloc[2:4,0:2]
# 2:4--> rows 
# 0:2--> columns 
#  if we have to take the output form the  df as 8 9 12 13

column1  column2
row3        8        9
row4       12       13

In [22]:
df.iloc[2:,1:]

column2  column3  column4
row3        9       10       11
row4       13       14       15
row5       17       18       19

In [23]:
df.iloc[0:4,0:1]

column1
row1        0
row2        4
row3        8
row4       12

In [24]:
df.iloc[0:4,3:4]

column4
row1        3
row2        7
row3       11
row4       15

In [25]:
df.iloc[:,1:]

column2  column3  column4
row1        1        2        3
row2        5        6        7
row3        9       10       11
row4       13       14       15
row5       17       18       19

In [26]:
# to convert the dataframe into array

In [27]:
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [28]:
# basic operation
df

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [29]:
# null values
df.isnull()

column1  column2  column3  column4
row1    False    False    False    False
row2    False    False    False    False
row3    False    False    False    False
row4    False    False    False    False
row5    False    False    False    False

In [30]:
# taking sum of null values 
df.isnull().sum()

column1    0
column2    0
column3    0
column4    0
dtype: int64

In [31]:
# dataframe creation
# np.nan, gives the null value (NaN--> not a number )
df=pd.DataFrame(data=[[1,np.nan,2],[1,2,3]],index=['row1','row2']
             ,columns=["column1","column2","column3"])

In [32]:
df

column1  column2  column3
row1        1      NaN        2
row2        1      2.0        3

In [33]:
# checking the null value and sum 
df.isnull().sum()

column1    0
column2    1
column3    0
dtype: int64

In [34]:
df.isnull().sum()==0

column1     True
column2    False
column3     True
dtype: bool

In [35]:
df.isnull().sum==0

False

In [36]:
df["column3"].value_counts()

2    1
3    1
Name: column3, dtype: int64

In [37]:
df["column3"].unique()

array([2, 3], dtype=int64)

In [38]:
df>2 # gives true when the value is greater then 2

column1  column2  column3
row1    False    False    False
row2    False    False     True

In [39]:
df[df['column2']>1]

column1  column2  column3
row2        1      2.0        3